#! /bin/bash

# Start the hotkey daemon ~/.config/sxhkd/sxhkdrc
killall sxhkd
sxhkd &


# Setup "Desktops" (workspaces) and make sure monitors are in order
if xrandr | grep 'eDP-1 connected'; then
    if xrandr | grep '^DP-1 connected'; then
        . ~/.config/bspwm/frameworkmonrc
    else
        . ~/.config/bspwm/frameworkrc
    fi
    "$HOME/.config/polybar/nord/launch.sh" dark framework
else
    bspc monitor DisplayPort-0 -d main browser workbrowser media five six zoom eight
    bspc monitor HDMI-A-0 -d slack
    "$HOME/.config/polybar/nord/launch.sh" dark
    xrandr --output DisplayPort-0 --set TearFree on
    xrandr --output HDMI-A-0 --set TearFree on
fi

# Everything below came as default
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a URxvt:urxvt-fuzzy state=floating sticky=on center=on monitor=C
bspc rule -a URxvt:urxvt-float state=floating sticky=on center=on monitor=C
bspc rule -a URxvt:urxvt-scratch state=floating sticky=on center=on monitor=C
bspc rule -a feh state=floating
bspc rule -a Zathura state=tiled

# Firefox to desktop #2
bspc rule -a *:Navigator desktop='browser'

# Work firefox to desktop #3
bspc rule -a browser-work desktop='workbrowser'

# Media desktop #4
bspc rule -a mpv desktop='media'
bspc rule -a *:music desktop='media'

# Work vpn firefox to desktop #5
bspc rule -a browser-vpn desktop='five'

# Zoom desktop #7
bspc rule -a zoom desktop='zoom'
bspc rule -a Skype desktop='zoom'

# Slack to side monitor, desktop #9
bspc rule -a Slack desktop='slack' focus=off

bspc config external_rules_command ~/.config/bspwm/external_rules.sh
